shallow_clone: true
clone_folder: C:\projects\ElonaFoobar

os:
  - Visual Studio 2017

environment:
  matrix:
  - CMAKE_ARGS: -G "Visual Studio 15 2017 Win64"
    BOOST_VERSION: 1.66.0
    BOOST_ROOT: C:\Libraries\boost_1_69_0
    PREFIX: C:\SDK

build:
  verbosity: detailed

configuration:
  - Debug


# for master branch
for:
-
  branches:
    only:
      - master

  configuration:
    - Release


branches:
  except:
    - /pr\/.+/

cache:
  C:\SDK -> appveyor.yml

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - cd C:\projects\ElonaFoobar
  - if exist %PREFIX% set NEEDDEPENDS=rem
  - |-
    %NEEDDEPENDS% cp deps\install.bat %PREFIX%
    %NEEDDEPENDS% cd %PREFIX%
    %NEEDDEPENDS% git clone https://www.github.com/Ruin0x11/foobar_windows_deps windows
    %NEEDDEPENDS% call .\install.bat

build_script:
  - chcp 65001
  - cd %PREFIX%
  - appveyor DownloadFile http://ylvania.style.coocan.jp/file/elona122.zip
  - 7z x -y elona122.zip > nul
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir bin
  - cd bin
  - cmake -DCMAKE_PREFIX_PATH=%PREFIX% -DELONA_BUILD_TARGET=TESTS %CMAKE_ARGS% -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..
  - cmake --build . --config %CONFIGURATION%
  - cd %CONFIGURATION%
  - Elona_foobar.exe --durations=yes
  - cd %APPVEYOR_BUILD_FOLDER%\bin
  - cmake -DCMAKE_PREFIX_PATH=%PREFIX% -DELONA_BUILD_TARGET=GAME %CMAKE_ARGS% -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..
  - cmake --build . --config %CONFIGURATION%
  - cmake -DCMAKE_PREFIX_PATH=%PREFIX% -DELONA_BUILD_TARGET=LAUNCHER %CMAKE_ARGS% -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..
  - cmake --build . --config %CONFIGURATION%

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mv bin\%CONFIGURATION% bin\Elona_foobar
  - mv CHANGELOG*.md bin\Elona_foobar
  - mv LICENSE.txt bin\Elona_foobar
  - mv CREDITS.txt bin\Elona_foobar
  - del bin\Elona_foobar\*.ilk
  - del bin\Elona_foobar\*.pdb
  - rd /q /s bin\Elona_foobar\graphic
  - rd /q /s bin\Elona_foobar\log
  - rd /q /s bin\Elona_foobar\save
  - rd /q /s bin\Elona_foobar\sound
  - rd /q /s bin\Elona_foobar\tests
  - rd /q /s bin\Elona_foobar\tmp
  - rd /q /s bin\Elona_foobar\user
  - xcopy /s /e /y runtime\* bin\Elona_foobar
  - ps: "$env:ELONAFOOBAR_VERSION=(Select-String 'project\\(Elona_foobar VERSION (.*)\\)' CMakeLists.txt).Matches.Groups[1].Value"
  - cd bin
  - ren Elona_foobar\Elona_foobar.exe "Elona foobar.exe"
  - ren Elona_foobar "Elona foobar v%ELONAFOOBAR_VERSION%"
  - 7z a -y "Elona foobar v%ELONAFOOBAR_VERSION% (Windows).zip" "Elona foobar v%ELONAFOOBAR_VERSION%"

artifacts:
  - path: 'bin\Elona foobar v* (Windows).zip'

