#pragma once


#define inv_number(x) inv(0, (x))
#define inv_value(x) inv(1, (x))
#define inv_image(x) inv(2, (x))
#define inv_id(x) inv(3, (x))
#define inv_quality(x) inv(4, (x))
#define inv_x(x) inv(5, (x))
#define inv_y(x) inv(6, (x))
#define inv_weight(x) inv(7, (x))
#define inv_identification_state(x) inv(8, (x))
#define inv_count(x) inv(9, (x))
#define inv_dice_x(x) inv(10, (x))
#define inv_dice_y(x) inv(11, (x))
#define inv_damage_bonus(x) inv(12, (x))
#define inv_hit_bonus(x) inv(13, (x))
#define inv_dv(x) inv(14, (x))
#define inv_pv(x) inv(15, (x))
#define inv_skill(x) inv(16, (x))
#define inv_curse_state(x) inv(17, (x))
#define inv_body_part(x) inv(18, (x))
#define inv_function(x) inv(19, (x))
#define inv_enhancement(x) inv(20, (x))
#define inv_own_state(x) inv(21, (x))
#define inv_color(x) inv(22, (x))
#define inv_subname(x) inv(23, (x))
#define inv_material(x) inv(24, (x))
#define inv_param1(x) inv(25, (x))
#define inv_param2(x) inv(26, (x))
#define inv_param3(x) inv(27, (x))
#define inv_param4(x) inv(28, (x))
#define inv_difficulty_of_identification(x) inv(29, (x))
#define inv_turn(x) inv(30, (x))

#define inv_enchantment_id(x, i) inv(40 + (i)*2, (x))
#define inv_enchantment_power(x, i) inv(40 + (i)*2 + 1, (x))
