#pragma once


#define cdata_state(x) cdata(0, x)
#define cdata_x(x) cdata(1, x)
#define cdata_y(x) cdata(2, x)
#define cdata_next_x(x) cdata(3, x)
#define cdata_next_y(x) cdata(4, x)
#define cdata_time_to_revive(x) cdata(5, x)
#define cdata_vision_flag(x) cdata(6, x)
#define cdata_image(x) cdata(7, x)
#define cdata_sex(x) cdata(8, x)
#define cdata_relationship(x) cdata(9, x)
#define cdata_turn_cost(x) cdata(10, x)
#define cdata_current_speed(x) cdata(11, x)
#define cdata_item_which_will_be_used(x) cdata(12, x)
#define cdata_portrait(x) cdata(13, x)
#define cdata_interest(x) cdata(14, x)
#define cdata_time_interest_revive(x) cdata(15, x)
#define cdata_personality(x) cdata(16, x)
#define cdata_impression(x) cdata(17, x)
#define cdata_talk_type(x) cdata(18, x)
#define cdata_height(x) cdata(19, x)
#define cdata_weight(x) cdata(20, x)
#define cdata_birth_year(x) cdata(21, x)
#define cdata_nutrition(x) cdata(22, x)
#define cdata_can_talk(x) cdata(23, x)
#define cdata_quality(x) cdata(25, x)
#define cdata_turn(x) cdata(26, x)
#define cdata_id(x) cdata(27, x)
#define cdata_vision_distance(x) cdata(28, x)
#define cdata_enemy_id(x) cdata(29, x)
#define cdata_gold(x) cdata(30, x)
#define cdata_platinum_coin(x) cdata(31, x)
#define cdata_equipment_type(x) cdata(32, x)
#define cdata_melee_attack_type(x) cdata(33, x)
#define cdata_fame(x) cdata(34, x)
#define cdata_experience(x) cdata(35, x)
#define cdata_required_experience(x) cdata(36, x)
#define cdata_speed_percentage(x) cdata(37, x)
#define cdata_level(x) cdata(38, x)
#define cdata_speed_percentage_in_next_turn(x) cdata(39, x)
#define cdata_skill_bonus(x) cdata(41, x)
#define cdata_total_skill_bonus(x) cdata(42, x)
#define cdata_inventory_weight(x) cdata(43, x)
#define cdata_max_inventory_weight(x) cdata(44, x)
#define cdata_inventory_weight_type(x) cdata(45, x)
#define cdata_max_level(x) cdata(48, x)
#define cdata_karma(x) cdata(49, x)
#define cdata_hp(x) cdata(50, x)
#define cdata_max_hp(x) cdata(51, x)
#define cdata_sp(x) cdata(52, x)
#define cdata_max_sp(x) cdata(53, x)
#define cdata_mp(x) cdata(55, x)
#define cdata_max_mp(x) cdata(56, x)
#define cdata_heal_value_per_nether_attack(x) cdata(60, x)
#define cdata_god(x) cdata(61, x)
#define cdata_piety_point(x) cdata(62, x)
#define cdata_praying_point(x) cdata(63, x)
#define cdata_sum_of_equipment_weight(x) cdata(64, x)
#define cdata_special_attack_type(x) cdata(65, x)
#define cdata_rate_to_pierce(x) cdata(66, x)
#define cdata_rate_of_critical_hit(x) cdata(67, x)
#define cdata_speed_correction_value(x) cdata(68, x)
#define cdata_original_relationship(x) cdata(69, x)
#define cdata_pv(x) cdata(70, x)
#define cdata_dv(x) cdata(71, x)
#define cdata_hit_bonus(x) cdata(72, x)
#define cdata_damage_bonus(x) cdata(73, x)
#define cdata_pv_correction_value(x) cdata(76, x)
#define cdata_dv_correction_value(x) cdata(77, x)
#define cdata_damage_reaction_info(x) cdata(78, x)
#define cdata_emotion_icon(x) cdata(79, x)
#define cdata_current_map(x) cdata(80, x)
#define cdata_current_dungeon_level(x) cdata(81, x)
#define cdata_related_quest_id(x) cdata(82, x)
#define cdata_direction(x) cdata(83, x)
#define cdata_period_of_contract(x) cdata(84, x)
#define cdata_hire_count(x) cdata(85, x)
#define cdata_insanity(x) cdata(86, x)
#define cdata_curse_power(x) cdata(87, x)
#define cdata_extra_attack(x) cdata(88, x)
#define cdata_extra_shot(x) cdata(89, x)
#define cdata_decrease_physical_damage(x) cdata(90, x)
#define cdata_nullify_damage(x) cdata(91, x)
#define cdata_cut_counterattack(x) cdata(92, x)
#define cdata_anorexia_count(x) cdata(93, x)
#define cdata_continuous_action_id(x) cdata(140, x)
#define cdata_continuous_action_turn(x) cdata(141, x)
#define cdata_continuous_action_item(x) cdata(142, x)
#define cdata_stops_continuous_action_if_damaged(x) cdata(143, x)
#define cdata_quality_of_performance(x) cdata(144, x)
#define cdata_tip_gold(x) cdata(145, x)
#define cdata_character_role(x) cdata(150, x)
#define cdata_shop_rank(x) cdata(151, x)
#define cdata_continuous_action_target(x) cdata(152, x)
#define cdata_shop_store_id(x) cdata(153, x)
#define cdata_time_to_restore(x) cdata(154, x)
#define cdata_cnpc_id(x) cdata(157, x)
#define cdata_initial_x(x) cdata(171, x)
#define cdata_initial_y(x) cdata(172, x)
#define cdata_hate(x) cdata(201, x)
#define cdata_ai_calm(x) cdata(202, x)
#define cdata_ai_move(x) cdata(207, x)
#define cdata_ai_dist(x) cdata(208, x)
#define cdata_ai_act_sub_freq(x) cdata(209, x)
#define cdata_ai_heal(x) cdata(211, x)
#define cdata_ai_act_num(x) cdata(212, x)
#define cdata_element_of_unarmed_attack(x) cdata(230, x)
#define cdata_poisoned(x) cdata(250, x)
#define cdata_sleep(x) cdata(251, x)
#define cdata_paralyzed(x) cdata(252, x)
#define cdata_blind(x) cdata(253, x)
#define cdata_confused(x) cdata(254, x)
#define cdata_fear(x) cdata(255, x)
#define cdata_dimmed(x) cdata(256, x)
#define cdata_drunk(x) cdata(257, x)
#define cdata_bleeding(x) cdata(258, x)
#define cdata_wet(x) cdata(259, x)
#define cdata_insane(x) cdata(260, x)
#define cdata_sick(x) cdata(261, x)
#define cdata_gravity(x) cdata(262, x)
#define cdata_choked(x) cdata(263, x)
#define cdata_furious(x) cdata(264, x)

#define cdata_growth_buff(x, i) cdata(270 + (i), x)

#define cdata_body_part(x, i) cdata(100 + (i), x)
#define cdata_body_part_inv(x, i) cdata(i, x)

#define cdata_ai_act(x, i) cdata(215 + (i), x)
#define cdata_ai_act_sub(x, i) cdata(220 + (i), x)

#define cdata_buff_id(x, i) cdata(280 + (i)*3, x)
#define cdata_buff_power(x, i) cdata(280 + (i)*3 + 1, x)
#define cdata_buff_turns(x, i) cdata(280 + (i)*3 + 2, x)

#define cdata_attr_adj(x, i) cdata(240 + i, x)

#define cdata_40(x) cdata(40, x)
#define cdata_158(x) cdata(158, x)

#define cdata_156(x) cdata(156, x)

#define cdata_203(x) cdata(203, x)
#define cdata_205(x) cdata(205, x)
#define cdata_206(x) cdata(206, x)
