namespace elona
{
inline elona_vector1<int> _randcolor;
inline elona_vector1<int> act_at_tcg;
inline elona_vector1<int> anip;
inline elona_vector1<int> aniref;
inline elona_vector1<int> anix;
inline elona_vector1<int> ap;
inline elona_vector1<int> arenaop;
inline elona_vector1<int> asettown;
inline elona_vector1<int> atxid;
inline elona_vector1<int> atxpic;
inline elona_vector1<int> ax2;
inline elona_vector1<int> ax;
inline elona_vector1<int> ay2;
inline elona_vector1<int> ay;
inline elona_vector1<int> bkdata;
inline elona_vector1<int> blendchecklist;
inline elona_vector1<int> bmpbuff;
inline elona_vector1<int> bodylist;
inline elona_vector1<int> cflist_at_tcg;
inline elona_vector1<int> chainbomblist;
inline elona_vector1<int> chatval;
inline elona_vector1<int> clistmax_at_tcg;
inline elona_vector1<int> cmlock;
inline elona_vector1<int> cmstats;
inline elona_vector1<int> commark;
inline elona_vector1<int> cpx_at_tcg;
inline elona_vector1<int> cpy_at_tcg;
inline elona_vector1<int> crlfs_at_crlf;
inline elona_vector1<int> cs_posbk;
inline elona_vector1<int> cyclemax;
inline elona_vector1<int> deck;
inline elona_vector1<int> deckix_at_tcg;
inline elona_vector1<int> deckiy_at_tcg;
inline elona_vector1<int> deckmode_at_tcg;
inline elona_vector1<int> deliver;
inline elona_vector1<int> dir;
inline elona_vector1<int> domain_at_tcg;
inline elona_vector1<int> drop;
inline elona_vector1<int> dx;
inline elona_vector1<int> dy_at_m133;
inline elona_vector1<int> egolist;
inline elona_vector1<int> evdata1;
inline elona_vector1<int> evdata2;
inline elona_vector1<int> evlist;
inline elona_vector1<int> feat;
inline elona_vector1<int> fishanime;
inline elona_vector1<int> fishdir;
inline elona_vector1<int> fixeditemenc;
inline elona_vector1<int> floorstack;
inline elona_vector1<int> followerexist;
inline elona_vector1<int> followerin;
inline elona_vector1<int> fsetarmor;
inline elona_vector1<int> fsetbarrel;
inline elona_vector1<int> fsetchest;
inline elona_vector1<int> fsetcollect;
inline elona_vector1<int> fsetdeliver;
inline elona_vector1<int> fsetincome;
inline elona_vector1<int> fsetitem;
inline elona_vector1<int> fsetmagic;
inline elona_vector1<int> fsetperform;
inline elona_vector1<int> fsetplantartifact;
inline elona_vector1<int> fsetplantunknown;
inline elona_vector1<int> fsetrare;
inline elona_vector1<int> fsetremain;
inline elona_vector1<int> fsetrewardsupply;
inline elona_vector1<int> fsetsupply;
inline elona_vector1<int> fsetweapon;
inline elona_vector1<int> fsetwear;
inline elona_vector1<int> gdata;
inline elona_vector1<int> genetemp;
inline elona_vector1<int> giftvalue;
inline elona_vector1<int> gmescol;
inline elona_vector1<int> graveix_at_tcg;
inline elona_vector1<int> graveiy_at_tcg;
inline elona_vector1<int> gravesum_at_tcg;
inline elona_vector1<int> holderix_at_tcg;
inline elona_vector1<int> holderiy_at_tcg;
inline elona_vector1<int> i;
inline elona_vector1<int> i_at_cardcontrol;
inline elona_vector1<int> icolref;
inline elona_vector1<int> id;
inline elona_vector1<int> idata;
inline elona_vector1<int> ilight;
inline elona_vector1<int> income;
inline elona_vector1<int> invcontainer;
inline elona_vector1<int> invctrl;
inline elona_vector1<int> invicon;
inline elona_vector1<int> invmark;
inline elona_vector1<int> iorgweight;
inline elona_vector1<int> ipicref;
inline elona_vector1<int> irandomname;
inline elona_vector1<int> isetbook;
inline elona_vector1<int> isetcrop;
inline elona_vector1<int> isetdeed;
inline elona_vector1<int> isetfruit;
inline elona_vector1<int> isetgiftgrand;
inline elona_vector1<int> isetgiftmajor;
inline elona_vector1<int> isetgiftminor;
inline elona_vector1<int> isetgod;
inline elona_vector1<int> isethire;
inline elona_vector1<int> isethirerole;
inline elona_vector1<int> isetthrowpotiongreater;
inline elona_vector1<int> isetthrowpotionmajor;
inline elona_vector1<int> isetthrowpotionminor;
inline elona_vector1<int> j;
inline elona_vector1<int> keybd_st;
inline elona_vector1<int> landix_at_tcg;
inline elona_vector1<int> landiy_at_tcg;
inline elona_vector1<int> landsum_at_tcg;
inline elona_vector1<int> list_at_m138;
inline elona_vector1<int> mainskill;
inline elona_vector1<int> mapclient;
inline elona_vector1<int> mat;
inline elona_vector1<int> matneed;
inline elona_vector1<int> mattile;
inline elona_vector1<int> matval;
inline elona_vector1<int> maze;
inline elona_vector1<int> mdata;
inline elona_vector1<int> mdatatmp;
inline elona_vector1<int> moneybox;
inline elona_vector1<int> n;
inline elona_vector1<int> p;
inline elona_vector1<int> p_at_cardcontrol;
inline elona_vector1<int> p_at_m188;
inline elona_vector1<int> p_at_m41;
inline elona_vector1<int> p_at_m47;
inline elona_vector1<int> p_at_m57;
inline elona_vector1<int> p_at_tcg;
inline elona_vector1<int> rainx;
inline elona_vector1<int> rainy;
inline elona_vector1<int> randcolor;
inline elona_vector1<int> rangemap;
inline elona_vector1<int> ranknorma;
inline elona_vector1<int> rddoorpos;
inline elona_vector1<int> rdval;
inline elona_vector1<int> recipememory;
inline elona_vector1<int> reph;
inline elona_vector1<int> repw;
inline elona_vector1<int> rowactre;
inline elona_vector1<int> rppage;
inline elona_vector1<int> rpref;
inline elona_vector1<int> rpsourcelist;
inline elona_vector1<int> rtval;
inline elona_vector1<int> sell;
inline elona_vector1<int> shadowmap;
inline elona_vector1<int> soundlist;
inline elona_vector1<int> spact;
inline elona_vector1<int> spell;
inline elona_vector1<int> spotiy_at_tcg;
inline elona_vector1<int> sx;
inline elona_vector1<int> sy;
inline elona_vector1<int> tc;
inline elona_vector1<int> tcol_at_txtfunc;
inline elona_vector1<int> tile;
inline elona_vector1<int> tile_default;
inline elona_vector1<int> tile_fog;
inline elona_vector1<int> tile_room;
inline elona_vector1<int> tile_tunnel;
inline elona_vector1<int> tile_wall;
inline elona_vector1<int> trait;
inline elona_vector1<int> traitref;
inline elona_vector1<int> trate;
inline elona_vector1<int> unaiactsubfreq;
inline elona_vector1<int> val;
inline elona_vector1<int> val_skill;
inline elona_vector1<int> voidboss;
inline elona_vector1<int> way;
inline elona_vector1<int> wh;
inline elona_vector1<int> windowshadow;
inline elona_vector1<int> x;
inline elona_vector1<int> x_at_tcg;
inline elona_vector1<int> y;
inline elona_vector1<int> y_at_tcg;
inline elona_vector1<std::string> _burden;
inline elona_vector1<std::string> _cast;
inline elona_vector1<std::string> _conangry;
inline elona_vector1<std::string> _conbleed;
inline elona_vector1<std::string> _condim;
inline elona_vector1<std::string> _confatigue;
inline elona_vector1<std::string> _coninsane;
inline elona_vector1<std::string> _conpoison;
inline elona_vector1<std::string> _consick;
inline elona_vector1<std::string> _consleep;
inline elona_vector1<std::string> _furniture;
inline elona_vector1<std::string> _homename;
inline elona_vector1<std::string> _hunger;
inline elona_vector1<std::string> _impression;
inline elona_vector1<std::string> _mark;
inline elona_vector1<std::string> _namepotion;
inline elona_vector1<std::string> _namering;
inline elona_vector1<std::string> _namescroll;
inline elona_vector1<std::string> _namespellbook;
inline elona_vector1<std::string> _namestaff;
inline elona_vector1<std::string> _onii;
inline elona_vector1<std::string> _quality;
inline elona_vector1<std::string> _resist;
inline elona_vector1<std::string> _reward;
inline elona_vector1<std::string> _sex2;
inline elona_vector1<std::string> _sex;
inline elona_vector1<std::string> _sleep;
inline elona_vector1<std::string> _stats2;
inline elona_vector1<std::string> _stats;
inline elona_vector1<std::string> _syujin;
inline elona_vector1<std::string> _time;
inline elona_vector1<std::string> _tone;
inline elona_vector1<std::string> _tone_at_m34;
inline elona_vector1<std::string> _weather;
inline elona_vector1<std::string> _weight;
inline elona_vector1<std::string> actlistn;
inline elona_vector1<std::string> ammoname;
inline elona_vector1<std::string> artifactlocation;
inline elona_vector1<std::string> atxinfon;
inline elona_vector1<std::string> bdrefn;
inline elona_vector1<std::string> biten;
inline elona_vector1<std::string> bodyn;
inline elona_vector1<std::string> booktitle;
inline elona_vector1<std::string> buff2;
inline elona_vector1<std::string> buff;
inline elona_vector1<std::string> buffboard;
inline elona_vector1<std::string> buffdesc;
inline elona_vector1<std::string> buffname;
inline elona_vector1<std::string> carddetailn_at_tcg;
inline elona_vector1<std::string> cardrefn;
inline elona_vector1<std::string> cdrefn_at_tcg;
inline elona_vector1<std::string> cellobjname;
inline elona_vector1<std::string> cfname_at_tcg;
inline elona_vector1<std::string> cgiurl2;
inline elona_vector1<std::string> cgiurl3;
inline elona_vector1<std::string> cmrace;
inline elona_vector1<std::string> csv;
inline elona_vector1<std::string> csvbuff;
inline elona_vector1<std::string> csvidx;
inline elona_vector1<std::string> cyclekey;
inline elona_vector1<std::string> description;
inline elona_vector1<std::string> domname_at_tcg;
inline elona_vector1<std::string> egominorn;
inline elona_vector1<std::string> egoname;
inline elona_vector1<std::string> file;
inline elona_vector1<std::string> file_cnv;
inline elona_vector1<std::string> filebuff;
inline elona_vector1<std::string> filebuff_at_m188;
inline elona_vector1<std::string> filemod;
inline elona_vector1<std::string> filetemp;
inline elona_vector1<std::string> filetemp_at_m188;
inline elona_vector1<std::string> filter_creature;
inline elona_vector1<std::string> filter_item;
inline elona_vector1<std::string> filtern;
inline elona_vector1<std::string> fishdatan;
inline elona_vector1<std::string> fltnrace;
inline elona_vector1<std::string> folder;
inline elona_vector1<std::string> gdatan;
inline elona_vector1<std::string> giftn;
inline elona_vector1<std::string> godname;
inline elona_vector1<std::string> headtemp;
inline elona_vector1<std::string> helpmsg_at_tcg;
inline elona_vector1<std::string> ialphanameref;
inline elona_vector1<std::string> iknownnameref;
inline elona_vector1<std::string> iname;
inline elona_vector1<std::string> inputlog2;
inline elona_vector1<std::string> inputlog;
inline elona_vector1<std::string> invkey;
inline elona_vector1<std::string> invtitle;
inline elona_vector1<std::string> ioriginalnameref2;
inline elona_vector1<std::string> ioriginalnameref;
inline elona_vector1<std::string> jkey;
inline elona_vector1<std::string> key;
inline std::string key_identify;
inline std::string key_pageup;
inline std::string key_pagedown;
inline std::string key_cancel;
inline std::string key_help;
inline std::string key_msglog;
inline std::string key_enter;
inline std::string key_save;
inline std::string key_north;
inline std::string key_northeast;
inline std::string key_east;
inline std::string key_southeast;
inline std::string key_south;
inline std::string key_southwest;
inline std::string key_west;
inline std::string key_northwest;
inline std::string key_skill;
inline std::string key_close;
inline std::string key_cast;
inline std::string key_drink;
inline std::string key_read;
inline std::string key_zap;
inline std::string key_fire;
inline std::string key_search;
inline std::string key_target;
inline std::string key_dig;
inline std::string key_wait;
inline std::string key_inventory;
inline std::string key_drop;
inline std::string key_get;
inline std::string key_wipe;
inline std::string key_charainfo;
inline std::string key_eat;
inline std::string key_wear;
inline std::string key_godown;
inline std::string key_goup;
inline std::string key_interact;
inline std::string key_rest;
inline std::string key_use;
inline std::string key_bash;
inline std::string key_open;
inline std::string key_dip;
inline std::string key_pray;
inline std::string key_offer;
inline std::string key_journal;
inline std::string key_material;
inline std::string key_quick;
inline std::string key_get2;
inline std::string key_trait;
inline std::string key_look;
inline std::string key_give;
inline std::string key_prev;
inline std::string key_next;
inline std::string key_quickinv;
inline std::string key_throw;
inline std::string key_esc;
inline int key_alt;
inline std::string key_mode;
inline std::string key_ammo;
inline std::string key_mode2;
inline elona_vector1<std::string> key_list;
inline elona_vector1<std::string> key_select;
inline elona_vector1<std::string> keylog;
inline elona_vector1<std::string> magebookn;
inline elona_vector1<std::string> matdesc;
inline elona_vector1<std::string> matname;
inline elona_vector1<std::string> mdatan;
inline elona_vector1<std::string> moneyboxn;
inline elona_vector1<std::string> msg;
inline elona_vector1<std::string> msgref;
inline elona_vector1<std::string> msgtemp;
inline elona_vector1<std::string> msgtempprev;
inline elona_vector1<std::string> musicfile;
inline elona_vector1<std::string> netbuf;
inline elona_vector1<std::string> newsbuff;
inline elona_vector1<std::string> phasen_at_tcg;
inline elona_vector1<std::string> playerheader;
inline elona_vector1<std::string> popostname;
inline elona_vector1<std::string> q;
inline elona_vector1<std::string> qname;
inline elona_vector1<std::string> randn1;
inline elona_vector1<std::string> randn2;
inline elona_vector1<std::string> rffilter_item;
inline elona_vector1<std::string> rn1;
inline elona_vector1<std::string> rn2;
inline elona_vector1<std::string> rpdatan;
inline elona_vector1<std::string> rtvaln;
inline elona_vector1<std::string> s1;
inline elona_vector1<std::string> s;
inline elona_vector1<std::string> s_at_tcg;
inline elona_vector1<std::string> select;
inline elona_vector1<std::string> serverlist;
inline elona_vector1<std::string> skilldesc;
inline elona_vector1<std::string> skillencdesc;
inline elona_vector1<std::string> skillname;
inline elona_vector1<std::string> soundfile;
inline elona_vector1<std::string> tname;
inline elona_vector1<std::string> traitrefn2;
inline elona_vector1<std::string> traitrefn;
inline elona_vector1<std::string> txtbuff;
inline elona_vector1<std::string> unres;
inline elona_vector1<std::string> untaglist;
inline elona_vector1<std::string> usertxt;
inline elona_vector1<std::string> valn;
inline elona_vector1<std::string> valn_skill;
inline elona_vector1<std::string> ziptmp1;
inline elona_vector1<std::string> ziptmp1_at_m188;
inline elona_vector1<std::string> ziptmp2;
inline elona_vector1<std::string> ziptmp2_at_m188;
inline elona_vector2<int> adata;
inline elona_vector2<int> bdataref;
inline elona_vector2<int> bdref;
inline elona_vector2<int> breathlist;
inline elona_vector2<int> c_col;
inline elona_vector2<int> card;
inline elona_vector2<int> card_at_cardcontrol;
inline elona_vector2<int> card_at_tcg;
inline elona_vector2<int> cardplayer_at_cardcontrol;
inline elona_vector2<int> cardstack_at_tcg;
inline elona_vector2<int> cbitorg;
inline elona_vector2<int> cdata2;
inline elona_vector2<int> cdata;
inline elona_vector2<int> cellobjdata;
inline elona_vector2<int> chipc;
inline elona_vector2<int> chipi;
inline elona_vector2<int> chipm;
inline elona_vector2<int> clist_at_tcg;
inline elona_vector2<int> cloud;
inline elona_vector2<int> cmapdata;
inline elona_vector2<int> cpdata_at_tcg;
inline elona_vector2<int> cycle;
inline elona_vector2<int> dblist;
inline elona_vector2<int> deco;
inline elona_vector2<int> dirchk;
inline elona_vector2<int> dirxy;
inline elona_vector2<int> dlist_at_tcg;
inline elona_vector2<int> efllist_at_tcg;
inline elona_vector2<int> egoenc;
inline elona_vector2<int> egoref;
inline elona_vector2<int> elist_at_tcg;
inline elona_vector2<int> encammoref;
inline elona_vector2<int> enclist;
inline elona_vector2<int> encprocref;
inline elona_vector2<int> encref;
inline elona_vector2<int> fdlist;
inline elona_vector2<int> fishdata;
inline elona_vector2<int> fovlist;
inline elona_vector2<int> fovmap;
inline elona_vector2<int> gravelist_at_tcg;
inline elona_vector1<int> eqhelm;
inline elona_vector1<int> eqweapon1;
inline elona_vector1<int> eqshield;
inline elona_vector1<int> eqrange;
inline elona_vector1<int> eqammo;
inline elona_vector1<int> eqweapon2;
inline elona_vector1<int> eqarmor;
inline elona_vector1<int> eqglove;
inline elona_vector1<int> eqboots;
inline elona_vector1<int> eqcloack;
inline elona_vector1<int> eqgirdle;
inline elona_vector1<int> eqring1;
inline elona_vector1<int> eqring2;
inline elona_vector1<int> eqamulet1;
inline elona_vector1<int> eqamulet2;
inline elona_vector2<int> inv2;
inline elona_vector2<int> inv;
inline elona_vector2<int> itemmemory;
inline elona_vector2<int> landlist_at_tcg;
inline elona_vector2<int> lightdata;
inline elona_vector2<int> list;
inline elona_vector2<int> mapsync;
inline elona_vector2<int> matref;
inline elona_vector2<int> matspot;
inline elona_vector2<int> medalbk;
inline elona_vector2<int> mef;
inline elona_vector2<int> mefsubref;
inline elona_vector2<int> mtbit;
inline elona_vector2<int> mtenc;
inline elona_vector2<int> mtlistleather;
inline elona_vector2<int> mtlistmetal;
inline elona_vector2<int> mtref;
inline elona_vector2<int> npcmemory;
inline elona_vector2<int> pcc;
inline elona_vector2<int> picfood;
inline elona_vector2<int> podata;
inline elona_vector2<int> qdata;
inline elona_vector2<int> racebit;
inline elona_vector1<int> roomexist;
inline elona_vector1<int> roomx;
inline elona_vector1<int> roomy;
inline elona_vector1<int> roomwidth;
inline elona_vector1<int> roomheight;
inline elona_vector1<int> roomexit;
inline elona_vector1<int> roomexitmax;
inline elona_vector1<int> roomentrancex;
inline elona_vector1<int> roomentrancey;
inline elona_vector2<int> rolebk;
inline elona_vector2<int> route;
inline elona_vector2<int> rpdata;
inline elona_vector2<int> sdata2;
inline elona_vector2<int> sdata;
inline elona_vector2<int> sdataref;
inline elona_vector2<int> slight;
inline elona_vector2<int> slightbk;
inline elona_vector2<int> userdata;
inline elona_vector2<std::string> _melee;
inline elona_vector2<std::string> actor;
inline elona_vector2<std::string> bufftxt;
inline elona_vector2<std::string> cardn_at_tcg;
inline elona_vector2<std::string> cdatan2;
inline elona_vector2<std::string> cdatan;
inline elona_vector2<std::string> listn;
inline elona_vector2<std::string> mapnamerd;
inline elona_vector2<std::string> mtname;
inline elona_vector2<std::string> promptl;
inline elona_vector2<std::string> rankn;
inline elona_vector2<std::string> rfnameorg;
inline elona_vector2<std::string> rnlist;
inline elona_vector2<std::string> userdatan;
inline elona_vector3<int> bddata;
inline elona_vector3<int> efmap;
inline elona_vector3<int> map;
inline elona_vector3<int> pochart;
inline int _bold;
inline int _hole;
inline int _mclass;
inline int _stat_at_filedialog;
inline int a;
inline int a_at_m138;
inline int a_at_m63;
inline int a_at_tcg;
inline int acnt2;
inline int act;
inline int af;
inline int aiblock_at_tcg;
inline int allyctrl;
inline int am;
inline int ammo;
inline int ammoproc;
inline int ammox;
inline int ammoy;
inline int anic;
inline int anicol;
inline int anidx;
inline int anidy;
inline int anih;
inline int animeid;
inline int animode;
inline int anisound;
inline int aniw;
inline int aniy;
inline int ap2;
inline int ap3;
inline int area;
inline int arenaimport;
inline int attackitem;
inline int attacknum;
inline int attackrange;
inline int attackskill;
inline int attacktarget_at_tcg;
inline int attackvar;
inline int atxap;
inline int atxlv;
inline int atxrefval1;
inline int atxspot;
inline int atxthrough;
inline int automove;
inline int autosave;
inline int autoturn;
inline int ax_at_modfov;
inline int ay_at_modfov;
inline int baseh_at_tcg;
inline int basew_at_tcg;
inline int basex_at_tcg;
inline int basey_at_tcg;
inline int blendtool;
inline int blockedbychara;
inline int body;
inline int body_at_m38;
inline int bonus;
inline int breathw;
inline int c;
inline int c_at_cardcontrol;
inline int c_at_tcg;
inline int camera;
inline int cansee;
inline int cardholdermax_at_cardcontrol;
inline int cardmax_at_cardcontrol;
inline int cardmode_at_tcg;
inline int cardplayermax_at_cardcontrol;
inline int cardrefattack;
inline int cardrefbg;
inline int cardrefcost;
inline int cardrefdomain;
inline int cardrefhp;
inline int cardrefpic;
inline int cardrefrare;
inline int cardrefskill;
inline int cardrefskillcost;
inline int cardreftype;
inline int cardround;
inline int catitem;
inline int cc;
inline int cc_at_tcg;
inline int ccbk;
inline int ccf_at_tcg;
inline int ccprev;
inline int ccthrowpotion;
inline int cdatanfix;
inline int cdsummon_at_tcg;
inline int cellaccess;
inline int cellchara;
inline int cellfeat;
inline int cequipment;
inline int cfg_alert;
inline int cfg_alwayscenter;
inline int cfg_animewait;
inline int cfg_attackanime;
inline int cfg_attackwait;
inline int cfg_autonumlock;
inline int cfg_autoturn;
inline int cfg_chaintime;
inline int cfg_env;
inline int cfg_exanime;
inline int cfg_exlog;
inline int cfg_extrahelp;
inline int cfg_extrarace;
inline int cfg_fullscreen2;
inline int cfg_fullscreen;
inline int cfg_heart;
inline int cfg_hideautoidentify;
inline int cfg_hideshopresult;
inline int cfg_ignoredislike;
inline int cfg_joypad;
inline int cfg_language;
inline int cfg_msg_box;
inline int cfg_msgaddtime;
inline int cfg_msgtrans;
inline int cfg_music2;
inline int cfg_music;
inline int cfg_net;
inline int cfg_netchat;
inline int cfg_netwish;
inline int cfg_objectshadow;
inline int cfg_runscroll;
inline int cfg_runwait;
inline int cfg_scancel;
inline int cfg_scroll;
inline int cfg_scrsync;
inline int cfg_serverlist;
inline int cfg_shadow;
inline int cfg_showskillmod;
inline int cfg_skiprandevents;
inline int cfg_sound2;
inline int cfg_sound;
inline int cfg_startrun;
inline int cfg_story;
inline int cfg_svolume;
inline int cfg_titleeffect;
inline int cfg_wait1;
inline int cfg_walkwait;
inline int cfg_windowanime;
inline int cfg_wizard;
inline int cfg_xkey;
inline int cfg_zkey;
inline int cfmax_at_tcg;
inline int ch_at_tcg;
inline int chainbomb;
inline int chaincontinue_at_tcg;
inline int chainmode_at_tcg;
inline int chainx_at_tcg;
inline int chainy_at_tcg;
inline int characreatehack;
inline int chararefreshhack;
inline int chatdeny;
inline int chatesc;
inline int chatflag;
inline int chatid;
inline int chatpicloaded;
inline int chatteleport;
inline int chatturn;
inline int ci;
inline int ci_at_m138;
inline int cibk;
inline int cibkread;
inline int cidip;
inline int cieat;
inline int citrade;
inline int city;
inline int cl_at_tcg;
inline int client;
inline int cm;
inline int cmbg;
inline int cmportrait;
inline int cmsex;
inline int cmshade;
inline int cnt2;
inline int cnt2_at_tcg;
inline int cnt;
inline int comctrl;
inline int cooktool;
inline int cost_at_m153;
inline int countdig;
inline int countequip;
inline int cp_at_tcg;
inline int cpicref;
inline int cr;
inline int creaturepack;
inline int critical;
inline int crlftype_at_crlf;
inline int crop;
inline int cs;
inline int cs_at_tcg;
inline int cs_bk2;
inline int cs_bk;
inline int cs_buff;
inline int cs_buffmax;
inline int cs_prev;
inline int csctrl;
inline int csline_at_tcg;
inline int cslinebk_at_tcg;
inline int cspecialeq;
inline int csprev;
inline int csskill;
inline int csvmax;
inline int ct;
inline int ct_at_tcg;
inline int cun;
inline int curdeck;
inline int curmenu;
inline int cursor_at_tcg;
inline int customer;
inline int cv;
inline int cw;
inline int cxbk;
inline int cxinit;
inline int cybk;
inline int cyinit;
inline int damage;
inline int damagenormal;
inline int damagepierce;
inline int dbg_compare;
inline int dbg_exitshowroom;
inline int dbg_freemove;
inline int dbg_revealmap;
inline int dbg_skipevent;
inline int dbgchara;
inline int dbid;
inline int dblistmax;
inline int dbmode;
inline int dbspec;
inline int decksizebk_at_tcg;
inline int deco2;
inline int dest_at_m168;
inline int dice1;
inline int dice2;
inline int digno;
inline int digx;
inline int digy;
inline int dir2_at_m168;
inline int dir_at_m168;
inline int dirsub;
inline int distance;
inline int dlistmax_at_tcg;
inline int dmg;
inline int dmg_at_m141;
inline int dmgfix;
inline double dmgmulti;
inline int dropcontinue;
inline int dropval;
inline int dsc_at_tcg;
inline int dump_return;
inline int dur;
inline int dx_at_cardcontrol;
inline int dx_at_m133;
inline int dx_at_m136;
inline int dx_at_m170;
inline int dx_at_modfov;
inline int dy;
inline int dy_at_cardcontrol;
inline int dy_at_m136;
inline int dy_at_m170;
inline int dy_at_modfov;
inline int ef;
inline int efbad;
inline int efcancel;
inline int efcibk;
inline int efid;
inline int efidprev;
inline int efllistmax_at_tcg;
inline int efp;
inline int efsource;
inline int efstatus;
inline int egg;
inline int egolv;
inline int ele;
inline int elep;
inline int elona_export;
inline int emax_at_tcg;
inline int en;
inline int enc2;
inline int enc;
inline int enc_at_m48;
inline int encounter;
inline int encounterlv;
inline int encounterref;
inline int encp_at_m48;
inline int enemylv;
inline int enemyteam;
inline int env;
inline int envonly;
inline int envwprev;
inline int ep;
inline int eqdup;
inline int eqmultiweapon;
inline int eqtwohand;
inline int eqtwowield;
inline int equip;
inline int evade;
inline int evaderef;
inline int evnum;
inline int evproc;
inline int evscrh;
inline int evscrw;
inline int evscry;
inline int evtiles;
inline int evx;
inline int evy;
inline int exp;
inline int exp_at_m77;
inline int expmodifer;
inline int extraattack;
inline int f1_at_modfov;
inline int f2;
inline int f2_at_modfov;
inline int f;
inline int f_at_con;
inline int f_at_m125;
inline int f_at_m138;
inline int f_at_m14;
inline int f_at_m53;
inline int f_at_m54;
inline int f_at_tcg;
inline int fdmax;
inline int featrq;
inline int fidx;
inline int filtermax;
inline int findlocmode;
inline int firstautoturn;
inline int firstturn;
inline int fish;
inline int fishstat;
inline int fishx;
inline int fishy;
inline int fixeq;
inline int fixlv;
inline int fixmaterial;
inline int fixstart;
inline int fixtransfermap;
inline int fltbk;
inline int fltselect;
inline int flttypemajor;
inline int flttypeminor;
inline int foot;
inline int fread;
inline int fsize;
inline int ghelp;
inline int gmestype;
inline int gmesw;
inline int gmesx;
inline int gmesy;
inline int gold;
inline int gravespace_at_tcg;
inline int grown;
inline int growth_at_m77;
inline int gspd;
inline int gspdorg;
inline int h;
inline int haveweapon;
inline int header;
inline int hear;
inline int hgz;
inline int himc_at_ime_control;
inline int hire;
inline int hit;
inline int holderspace_at_tcg;
inline int homemakewall;
inline int homemapmode;
inline int hour_played;
inline int hwnd;
inline int i_at_crlf;
inline int i_at_m145;
inline int i_at_m38;
inline int i_at_m66;
inline int i_at_m79;
inline int i_at_tcg;
inline int ichargelevel;
inline int idcupsule;
inline int idtresult;
inline int ie;
inline int ie_event;
inline int ieopen;
inline int ii_p;
inline int ime_esc;
inline int importmode;
inline int in;
inline int inf_barh;
inline int inf_bary;
inline int inf_clockarrowx;
inline int inf_clockarrowy;
inline int inf_clockh;
inline int inf_clockw;
inline int inf_clockx;
inline int inf_clocky;
inline int inf_hpx;
inline int inf_hpy;
inline int inf_maxlog;
inline int inf_maxmsglen;
inline int inf_mesfont;
inline int inf_mpx;
inline int inf_mpy;
inline int inf_msgh;
inline int inf_msgline;
inline int inf_msgspace;
inline int inf_msgx;
inline int inf_msgy;
inline int inf_raderw;
inline int inf_raderx;
inline int inf_radery;
inline int inf_screenh;
inline int inf_screenw;
inline int inf_screenx;
inline int inf_screeny;
inline int inf_tiles;
inline int inf_ver;
inline int inf_verh;
inline int inf_vertype;
inline int inf_very;
inline int inhmax;
inline int initeco;
inline int initlv;
inline int initnum;
inline int initunid;
inline int input_mode;
inline int inputfail;
inline int inumbk;
inline int invally;
inline int invfile;
inline int invhead;
inline int invrange;
inline int invsc;
inline int invsubroutine;
inline int itemcreatehack;
inline int itemdensity;
inline int itemnamehack;
inline int j_at_m193;
inline int jp;
inline int kdx;
inline int kdy;
inline int key_ctrl;
inline int key_escape;
inline int key_shift;
inline int key_tab;
inline int keybd_attacking;
inline int keybd_wait;
inline int keyhalt;
inline int keyrange;
inline int keywait;
inline int landspace_at_tcg;
inline int lastchat;
inline int lastctrl;
inline int lasttc;
inline int len;
inline int len_at_crlf;
inline int len_at_m188;
inline int lenhead;
inline int lenhead_at_m188;
inline int lensum;
inline int lensum_at_m188;
inline int levelexitby;
inline int listmax;
inline int livestock;
inline int lomiaseaster;
inline int lootrich;
inline int losmode;
inline int lv;
inline int lv_at_m77;
inline int lvchange_at_m77;
inline int lx;
inline int ly;
inline int m_at_modfov;
inline int mainhand;
inline int mainweapon;
inline int mapstartx;
inline int mapstarty;
inline int mapsubroutine;
inline int mapupdate;
inline int marry;
inline int matid;
inline int matnum;
inline int matuse;
inline int max_at_m138;
inline int maxbreath;
inline int maxcard_at_tcg;
inline int maxegominorn;
inline int maxitemid;
inline int maxmedal;
inline int maxnpcbk;
inline int maxnpcid;
inline int maxobjid;
inline int maxrain;
inline int maxroute;
inline int mdig;
inline int medit;
inline int menucycle;
inline int minlevel;
inline int mobdensity;
inline int mode;
inline int mousel;
inline int mousemove;
inline int mousex;
inline int mousey;
inline int movelevelbystairs;
inline int movx;
inline int movy;
inline int mp3;
inline int mp;
inline int msg_len;
inline int msgalert;
inline int msgclear;
inline int msgconfirm;
inline int msgdup;
inline int msgkeep;
inline int msglen;
inline int msgline;
inline int msgx;
inline int msgy;
inline int msync;
inline int mtilefilecur;
inline int mtlv;
inline int music;
inline int musicloop;
inline int musicprev;
inline int mustequip;
inline int mutch_at_filedialog;
inline int mutex_handle;
inline int n_at_m174;
inline int n_at_tcg;
inline int n_at_txtfunc;
inline int nerve;
inline int noaggrorefresh;
inline int noeffect;
inline int nojoker;
inline int nooracle;
inline int nostack;
inline int novoidlv;
inline int nowindowanime;
inline int npccostmp;
inline int nutrition;
inline int objfix;
inline int objlv;
inline int obvious;
inline int obvisou;
inline int obvjlv;
inline int oc;
inline int orgdmg;
inline int originalvalue;
inline int p1;
inline int p1_len_at_filedialog;
inline int p2;
inline int p3;
inline int p3_len_at_filedialog;
inline int p_at_con;
inline int p_at_m117;
inline int p_at_m138;
inline int p_at_m153;
inline int p_at_m170;
inline int p_at_m193;
inline int p_at_m34;
inline int p_at_m43;
inline int p_at_m48;
inline int p_at_m77;
inline int p_at_txtfunc;
inline int page;
inline int page_at_tcg;
inline int page_bk;
inline int pagebk;
inline int pagemax;
inline int pagesaved;
inline int pagesize;
inline int pcattacker;
inline int pcnoise;
inline int performtips;
inline int petarenawin;
inline int phase_at_tcg;
inline int pierce;
inline int pilex_at_cardcontrol;
inline int piley_at_cardcontrol;
inline int placefail;
inline int plat;
inline int player_at_tcg;
inline int pmdig;
inline int potionspill;
inline int potionthrow;
inline int probeq;
inline int prodtype;
inline int promptmax;
inline int promptx;
inline int prompty;
inline int prot2;
inline int prot;
inline int protdice1;
inline int protdice2;
inline int protfix;
inline int questteleport;
inline int quickkeywait;
inline int quickpage;
inline int qx_at_modfov;
inline int qy_at_modfov;
inline int r1;
inline int r2;
inline int r3;
inline int r4;
inline int r;
inline int racount;
inline int raderh;
inline int raderw;
inline int raderx;
inline int radery;
inline int randseed;
inline int range_;
inline int rangedist;
inline int rankcur;
inline int rankorg;
inline int rapidmagic;
inline int rc;
inline int rdcreaturepack;
inline int rdextraroom;
inline int rdhiddenpath;
inline int rdmonsterhouse;
inline int rdpos;
inline int rdroomdoor;
inline int rdroomdownstair;
inline int rdroomentrance;
inline int rdroomnum;
inline int rdroomsizemax;
inline int rdroomsizemin;
inline int rdroomupstair;
inline int rdsecond;
inline int rdsize;
inline int rdtry;
inline int rdtunnel;
inline int rdtype;
inline int rdx3;
inline int rdy3;
inline int ref1;
inline int ref2;
inline int refdiff;
inline int refreshmode;
inline int reftype;
inline int reftypeminor;
inline int refweight;
inline int refx;
inline int refy;
inline int regen;
inline int renewmulti;
inline int res_at_con;
inline int retreat;
inline int returnfromidentify;
inline int returnfromportrait;
inline int rewardfix;
inline int rh;
inline int ri;
inline int rollanatomy;
inline int roomdiff;
inline int roomdoor;
inline int roompos;
inline int roomsum;
inline int roomwall;
inline int rp2;
inline int rp3;
inline int rp;
inline int rpid;
inline int rpmode;
inline int rpresult;
inline int rq;
inline int rtdmg;
inline int rtval_at_tcg;
inline int running;
inline int rw;
inline int rx;
inline int ry;
inline int s_p;
inline int sac_at_tcg;
inline int save_f;
inline int save_p;
inline int sc;
inline int scene_cut;
inline int sceneid;
inline int scenemode;
inline int scidx;
inline int scidxtop;
inline int scposval;
inline int scposy;
inline int screendrawhack;
inline int screenmsgy;
inline int screenupdate;
inline int scroll;
inline int scrollanime;
inline int scrollp;
inline int scrturn;
inline int scx;
inline int scxbk2;
inline int scxbk;
inline int scy;
inline int scybk2;
inline int scybk;
inline int sdigx;
inline int sdigy;
inline int searchfov;
inline int sel;
inline int selcur;
inline int selectmode_at_tcg;
inline int sellgold;
inline int sexhost;
inline int sexvalue;
inline int shade;
inline int shoplv;
inline int shoptrade;
inline int showmoney;
inline int showresist;
inline int sid;
inline int size;
inline int sizefix;
inline int skip_at_m63;
inline int sold;
inline int sound;
inline int spd;
inline int spellbk;
inline int spellused_at_tcg;
inline int spotspace_at_tcg;
inline int stack_at_tcg;
inline int stake;
inline int start_at_filedialog;
inline int step;
inline int strsize;
inline int subdmg;
inline int subloop;
inline int submenu;
inline int supply;
inline int sx2;
inline int sx_at_modfov;
inline int sxfix;
inline int sy2;
inline int sy_at_modfov;
inline int syfix;
inline int t;
inline int tail;
inline int talkref;
inline int tc_at_m81;
inline int tcbk;
inline int tcchat;
inline int tchome;
inline int tcolfix_at_txtfunc;
inline int tcontinue_at_txtfunc;
inline int tcopy;
inline int tcprev;
inline int telex;
inline int teley;
inline int tg;
inline int tgloc;
inline int tglocx;
inline int tglocy;
inline int th_at_tcg;
inline int ti;
inline int ti_at_m138;
inline int tid;
inline int tile_battlesite;
inline int tile_board;
inline int tile_doorclosed2;
inline int tile_doorclosed3;
inline int tile_doorclosed4;
inline int tile_doorclosed;
inline int tile_dooropen;
inline int tile_downlocked;
inline int tile_downstairs;
inline int tile_dungeon;
inline int tile_hidden;
inline int tile_plant;
inline int tile_pot;
inline int tile_re;
inline int tile_roomlen;
inline int tile_townboard;
inline int tile_trans;
inline int tile_trap;
inline int tile_upstairs;
inline int tile_votebox;
inline int time_begin;
inline int time_warn;
inline int timeslept;
inline int tl_at_tcg;
inline int tlocinitx;
inline int tlocinity;
inline int tlocx;
inline int tlocy;
inline int tmat;
inline int tnew;
inline int tohi;
inline int tohit;
inline int tohitfix;
inline int tohitorg;
inline int tp_at_tcg;
inline int traitmode;
inline int traveldone;
inline int turn_at_tcg;
inline int turncost;
inline int twohit;
inline int tx;
inline int tx_at_m168;
inline int tx_at_modfov;
inline int txt3rd;
inline int txtadvmsgfix;
inline int txtadvscreenupdate;
inline int txtvalid;
inline int ty;
inline int ty_at_m168;
inline int ty_at_modfov;
inline int usermapid;
inline int usernpcmax;
inline int userrelation;
inline int value_at_m153;
inline int valuebk;
inline int vfix;
inline int voidlv;
inline int w;
inline int water_debug;
inline int weatherbk;
inline int windowh2;
inline int windowh;
inline int windoww2;
inline int windoww;
inline int windowx;
inline int windowy;
inline int winner;
inline int winrow;
inline int wishfilter;
inline int wishid;
inline int worker;
inline int ww;
inline int wx;
inline int wy;
inline int x1;
inline int x2;
inline int x2_at_m105;
inline int x_at_m169;
inline int x_at_txtfunc;
inline int y1;
inline int y2;
inline int y2_at_m105;
inline int y_at_m169;
inline int y_at_txtfunc;
inline int zipsize;
inline std::string _conblind;
inline std::string _conconfuse;
inline std::string _condrunk;
inline std::string _confear;
inline std::string _congravity;
inline std::string _conmochi;
inline std::string _conparalyze;
inline std::string _conwet;
inline std::string atbuff;
inline std::string atxbg;
inline std::string atxbgbk;
inline std::string bmpfile;
inline std::string buf;
inline std::string cardrefrace;
inline std::string cfg_font1;
inline std::string cfg_font2;
inline std::string chatnew;
inline std::string chatreadurl;
inline std::string chatsendurl;
inline std::string chattemp;
inline std::string classname;
inline std::string cmaka;
inline std::string cmclass;
inline std::string cmname;
inline std::string conurl_at_m147;
inline std::string dbidn;
inline std::string dbm;
inline std::string deckrefn_at_tcg;
inline std::string defload;
inline std::string devfile;
inline std::string filedsc;
inline std::string fileext;
inline std::string fmapfile;
inline std::string geneuse;
inline std::string gnname1;
inline std::string homepage;
inline std::string infilterref;
inline std::string key_alter;
inline std::string lastword;
inline std::string mid;
inline std::string midbk;
inline std::string msg_log;
inline std::string msgtemp_at_txtfunc;
inline std::string musicfolder;
inline std::string ndeathcause;
inline std::string note_buff;
inline std::string nquestdate;
inline std::string playerid;
inline std::string racename;
inline std::string refstr;
inline std::string s2;
inline std::string s_at_m174;
inline std::string s_at_m41;
inline std::string s_at_m63;
inline std::string save_buff;
inline std::string save_s;
inline std::string skilltmps;
inline std::string stramulet;
inline std::string strblank;
inline std::string strblessed;
inline std::string strbracketleft;
inline std::string strbracketright;
inline std::string strbye;
inline std::string strcursed;
inline std::string strdoomed;
inline std::string strfemale;
inline std::string strfix;
inline std::string strgold;
inline std::string strhint1;
inline std::string strhint2;
inline std::string strhint3;
inline std::string strhint3b;
inline std::string strhint4;
inline std::string strhint5;
inline std::string strhint5b;
inline std::string strhint6;
inline std::string strhint7;
inline std::string strinteractfail;
inline std::string strmale;
inline std::string strmore;
inline std::string strno;
inline std::string strnogold;
inline std::string strplat;
inline std::string strpotion;
inline std::string strring;
inline std::string strscroll;
inline std::string strsex;
inline std::string strspellbook;
inline std::string strstaff;
inline std::string strweight;
inline std::string stryes;
inline std::string szappfilter_at_filedialog;
inline std::string textreadurl;
inline std::string titlebuff;
inline std::string tmp;
inline std::string tmpbuf_at_crlf;
inline std::string tmpstr_at_crlf;
inline std::string txtcopy;
inline std::string txtfile;
inline std::string url_at_m147;
inline std::string userfile;
inline std::string usermsg;
inline std::string username;
inline std::string userpassword;
inline std::string usertitle;
inline std::string votereadurl;
inline std::string votesendurl;
inline std::string wincomment;
inline std::string zipfinalfile_at_m188;
inline std::string zipfolder_at_m188;
int actionsp(int = 0, int = 0);
int addbuff(int = 0, int = 0, int = 0, int = 0);
int advfavoriteskill(int = 0);
int advfavoritestat(int = 0);
int ai_check();
int blendcheckext(int = 0, int = 0);
int blendcheckmat(int = 0);
int blendmatnum(int = 0, int = 0);
int breath_list();
int calcattackdmg(int = 0);
int calcattackhit(int = 0);
int calccargoupdate();
int calccargoupdatecost();
int calccostbuilding();
int calccostreload(int = 0, int = 0);
int calccosttax();
int calcexpalive(int = 0);
int calcfame(int = 0, int = 0);
int calcfixlv(int = 0);
int calcguiltvalue(int = 0);
int calchireadv(int = 0);
int calchirecost(int = 0);
int calcidentifyvalue(int = 0);
int calcincome(int = 0);
int calcinitgold(int = 0);
int calcinvestvalue(int = 0);
int calcitemvalue(int = 0, int = 0);
int calclearncost(int = 0, int = 0, int = 0);
int calcmagiccontrol(int = 0, int = 0);
int calcmealvalue();
int calcmedalvalue(int = 0);
int calcobjlv(int = 0);
int calcrestorecost();
int calcresurrectvalue(int = 0);
int calcscore();
int calcshopreform();
int calcskill(int = 0, int = 0, int = 0);
int calcslavevalue(int = 0);
int calcspellcostmp(int = 0, int = 0);
int calcspellcoststock(int = 0, int = 0);
int calcspellfail(int = 0, int = 0);
int calcspellpower(int = 0, int = 0);
int calcstartcard(int = 0);
int calctraincost(int = 0, int = 0, int = 0);
int calcweaponfix(int = 0);
int card_ref(int = 0);
int cardcanblock(int = 0);
int cardcandeclareattack(int = 0);
int cardcanuseskill(int = 0);
int cargocheck();
int carmor(int = 0);
int cbit(int = 0, int = 0);
int cbreeder(int = 0);
int cdbit(int = 0, int = 0);
int cell_featread(int = 0, int = 0, int = 0);
int cell_findspace(int = 0, int = 0, int = 0);
int cell_itemlist(int = 0, int = 0);
int cell_itemoncell(int = 0, int = 0);
int chara_anorexia(int = 0);
int chara_unequip(int = 0);
int characreate(int = 0, int = 0, int = 0, int = 0);
int clientguide(int = 0);
int cnvjkey(const std::string&);
int convertartifact(int = 0, int = 0);
int copy_chara(int = 0);
int cpblackcard(int = 0);
int cpcardnum(int = 0);
int cpscore(int = 0);
int create_card(int = 0, int = 0);
int customtalk(int = 0, int = 0);
int decfame(int = 0, int = 0);
int direction(int = 0, int = 0, int = 0, int = 0);
int discsetmc();
int dist(int = 0, int = 0, int = 0, int = 0);
int dist_town();
int dmgcon(int = 0, int = 0, int = 0);
int dmghp(int = 0, int = 0, int = 0, int = 0, int = 0);
int dmgmp(int = 0, int = 0);
int dmgsan(int = 0, int = 0);
int dmgsp(int = 0, int = 0);
int efstatusfix(int = 0, int = 0, int = 0, int = 0);
int eleinfo(int = 0, int = 0);
int encadd(int = 0, int = 0, int = 0, int = 0, int = 0, int = 0, int = 0);
int encfind(int = 0, int = 0);
int encfindspec(int = 0, int = 0);
int encflt(int = 0, int = 0);
int eqweaponheavy();
int eqweaponlight();
int evfind(int = 0);
int evid();
int exist_questtarget();
int findally(int = 0);
int findbuff(int = 0, int = 0);
int findchara(int = 0);
int findunid(const std::string&);
int fltsetdungeon();
int fov_los(int = 0, int = 0, int = 0, int = 0);
int gameover();
int get_freeally();
int get_freechara();
int get_route(int = 0, int = 0, int = 0, int = 0);
int getdecksum(int = 0);
int getholdersum(int = 0);
int getspotsum(int = 0);
int getunid(int = 0);
int getworker(int = 0, int = 0);
int ibit(int = 0, int = 0);
int iequiploc(int = 0);
int imeget();
int implevel(int = 0);
int inv_find(int = 0, int = 0);
int inv_getfreeid(int = 0);
int inv_getowner(int = 0);
int inv_getspace(int = 0);
int inv_sum(int = 0);
int inv_weight_(int = 0);
int item_cold(int = 0, int = 0);
int item_find(int = 0, int = 0, int = 0);
int item_fire(int = 0, int = 0);
int item_identify(int = 0, int = 0, int = 0);
int item_separate(int&);
int item_stack(int = 0, int = 0, int = 0);
int itemcreate(int = 0, int = 0, int = 0, int = 0, int = 0);
int itemfind(int = 0, int = 0, int = 0);
int itemusingfind(int = 0, int = 0);
int key_direction();
int label_0042();
int label_0397();
int label_0410();
int label_1275();
int label_1280();
int label_1394();
int label_14002();
int label_1513();
int label_1514();
int label_1515();
int label_1517();
int label_1518();
int label_1533();
int label_1570();
int label_1582();
int label_1653();
int label_1656();
int label_1659();
int label_1663();
int label_1697();
int label_1698();
int label_1699();
int label_1700();
int label_1701();
int label_1702();
int label_1703();
int label_1747();
int label_1753();
int label_1756();
int label_1835();
int label_1845();
int label_1893();
int label_1896();
int label_1898();
int label_1931();
int label_1932();
int label_19432();
int label_1947();
int label_1959();
int label_196902();
int label_1980();
int label_1984();
int label_1993();
int label_2014();
int label_2018();
int label_20332();
int label_2039();
int label_2044();
int label_20592();
int label_2072();
int label_2073();
int label_2075();
int label_2080();
int label_2083();
int label_2107();
int label_2127();
int label_2131();
int label_2143();
int label_2163();
int label_2164();
int label_2167();
int label_2168();
int label_2169();
int label_2170();
int label_2171();
int label_2172();
int label_2174();
int label_2175();
int label_2176();
int label_2192();
int label_2193();
int label_2194();
int label_2209();
int label_2211();
int label_2217();
int label_2230();
int label_2231();
int label_2248();
int label_2297();
int label_2298();
int label_2659();
int label_2664();
int label_2665();
int label_2672();
int label_2694();
int label_2695();
int lastcard(int = 0);
int limitmax(int = 0, int = 0);
int map_barrel(int = 0, int = 0);
int map_connectroom();
int map_createroom(int = 0);
int map_digcheck(int = 0, int = 0);
int map_digtoentrance1(int = 0, int = 0, int = 0, int = 0, int = 0);
int map_placedownstairs(int = 0, int = 0);
int map_placeupstairs(int = 0, int = 0);
int map_trap(int = 0, int = 0, int = 0, int = 0);
int map_web(int = 0, int = 0, int = 0);
int mapitemfind(int = 0, int = 0, int = 0);
int modpiety(int = 0);
int net_dl(const std::string&, const std::string&);
int net_dllist(const std::string&, int = 0);
int net_read(int = 0);
int net_send(const std::string&, int = 0);
int opencard2(int = 0, int = 0);
int pileremain();
int prodcheck();
int putcard(int = 0, int = 0);
int randattb();
int random_material(int = 0, int = 0);
int randomele();
int randomenc(int = 0);
int randomenclv(int = 0);
int randomencp(int = 0);
int randskill();
int refchara(int = 0, int = 0);
int refclass(int = 0, int = 0);
int refitem(int = 0, int = 0);
int refrace(const std::string&, int = 0);
int relationbetween(int = 0, int = 0);
int relocate_chara(int = 0, int = 0, int = 0);
int role(int = 0, int = 0, int = 0);
int rolemax(int = 0, int = 0, int = 0);
int roundmargin(int = 0, int = 0);
int route_info(int&, int&, int = 0);
int rpdiff(int = 0, int = 0, int = 0);
int servecard(int = 0);
int sexp(int = 0, int = 0);
int sgrowth(int = 0, int = 0);
int skillexp(int = 0, int = 0, int = 0, int = 0, int = 0);
int skillmod(int = 0, int = 0, int = 0);
int sorg(int = 0, int = 0);
int synccheck(int = 0, int = 0);
int talk_conv(std::string&, int = 0);
int tradecheck(int = 0);
int trashcard(int = 0);
int winposy(int = 0, int = 0);
int zentohan(const std::string&, std::string&, int = 0);
std::string _aru(int = 0);
std::string _da(int = 0);
std::string _dana(int = 0);
std::string _daro(int = 0);
std::string _dozo(int = 0);
std::string _ga(int = 0);
std::string _ka(int = 0);
std::string _kana(int = 0);
std::string _kimi(int = 0);
std::string _kure(int = 0);
std::string _na(int = 0);
std::string _nda(int = 0);
std::string _noka(int = 0);
std::string _ore(int = 0);
std::string _rob(int = 0);
std::string _ru(int = 0);
std::string _s(int = 0, int = 0);
std::string _s2(int = 0);
std::string _ta(int = 0);
std::string _tanomu(int = 0);
std::string _thanks(int = 0);
std::string _u(int = 0);
std::string _yo(int = 0);
std::string _yoro(int = 0);
std::string aln(int = 0);
std::string cnv_str(std::string&, const std::string&, const std::string&);
std::string cnvarticle(const std::string&);
std::string cnvdate(int = 0, int = 0);
std::string cnven(const std::string&);
std::string cnveqweight(int = 0);
std::string cnvfix(int = 0);
std::string cnvitemname(int = 0);
std::string cnvplaytime(int = 0);
std::string cnvrank(int = 0);
std::string cnvrare(int = 0);
std::string cnvtalk(const std::string&);
std::string cnvweight(int = 0);
std::string del_str(const std::string&, const std::string&);
std::string does(int = 0);
std::string elename(int = 0);
std::string fixtxt(const std::string&, int = 0);
std::string fltname(int = 0);
std::string foodname(int, const std::string&, int = 0, int = 0);
std::string getnpctxt(const std::string&, const std::string&);
std::string guildname();
std::string have(int = 0);
std::string he(int = 0, int = 0);
std::string him(int = 0, int = 0);
std::string his(int = 0, int = 0);
std::string is(int = 0);
std::string is2(int = 0);
std::string itemname(int = 0, int = 0, int = 0);
std::string label_0225();
std::string lang(const std::string&, const std::string&);
std::string mapfile(int = 0);
std::string maplevel(int = 0);
std::string mapname(int = 0, int = 0);
std::string name(int = 0);
std::string npcn(int = 0);
std::string random_title(int = 0);
std::string randomname(int = 0);
std::string ranktitle(int = 0);
std::string refchara_str(int = 0, int = 0);
std::string rpmatname(int = 0);
std::string rpname(int = 0);
std::string rpsuccessrate(int = 0);
std::string sncnv(std::string&);
std::string trimdesc(const std::string&, int = 0);
std::string txtbuilding(int = 0, int = 0);
std::string txtitemoncell(int = 0, int = 0);
std::string txtskillchange(int = 0, int = 0, int = 0);
std::string your(int = 0, int = 0);
std::string yourself(int = 0);
void actionproc();
void addbuilding(int = 0, int = 0, int = 0, int = 0);
void addefmap(int = 0, int = 0, int = 0, int = 0, int = 0, int = 0);
void addmef(
    int = 0,
    int = 0,
    int = 0,
    int = 0,
    int = 0,
    int = 0,
    int = 0,
    int = 0,
    int = 0,
    int = 0);
void addnews(int = 0, int = 0);
void addnews2(const std::string&, int = 0);
void addnewstopic(const std::string&, const std::string&);
void anime_halt();
void animeblood(int = 0, int = 0, int = 0);
void animeload(int = 0, int = 0);
void arrayfile();
void at(int = 0);
void atxinit();
void begintempinv();
void bmes(const std::string&, int = 0, int = 0, int = 0);
void boxl(int = 0, int = 0, int = 0, int = 0);
void calcbuff(int = 0, int = 0, int = 0);
void calccosthire();
void calcdecksize();
void calcdomain();
void calcpartyscore();
void calcpartyscore2();
void calcstartattb(int = 0);
void cardhelp(const std::string&, int = 0);
void cardplayeradd(int = 0, int = 0, int = 0);
void cardplayerinit(int = 0, int = 0);
void cardpos(int = 0, int = 0);
void cbitmod(int = 0, int = 0, int = 0);
void cdbitmod(int = 0, int = 0, int = 0);
void cell_check(int = 0, int = 0);
void cell_draw();
void cell_featclear(int = 0, int = 0);
void cell_featset(int = 0, int = 0, int = 0, int = 0, int = 0, int = 0);
void cell_movechara(int = 0, int = 0, int = 0);
void cell_refresh(int = 0, int = 0);
void cell_removechara(int = 0, int = 0);
void cell_setchara(int = 0, int = 0, int = 0);
void cell_swap(int = 0, int = 0, int = 0, int = 0);
void chara_preparepic(int = 0, int = 0);
void chara_vanquish(int = 0);
void chara_vomit(int = 0);
void check_kill(int = 0, int = 0);
void check_quest();
void clear_rprefmat();
void cnv_filestr(std::string&);
void cnvbonus(int = 0, int = 0);
void colorres(int = 0);
void cpflip();
void cpisenemy();
void cpisme();
void create_pcpic(int = 0, int = 0);
void cs_listbk();
void csfix();
void cslinedown();
void cslineup();
void cure_anorexia(int = 0);
void cursor_check();
void cutname(std::string&, int = 0);
void del_chara(int = 0);
void delbottomcard(int = 0);
void delbuff(int = 0, int = 0);
void delmef(int = 0);
void dipcursed(int = 0, int = 0);
void display_customkey(const std::string&, int = 0, int = 0, int = 0);
void display_key(int = 0, int = 0, int = 0);
void display_msg(int = 0, int = 0);
void display_note(const std::string&, int = 0);
void display_topic(const std::string&, int = 0, int = 0, int = 0);
void display_window(int = 0, int = 0, int = 0, int = 0, int = 0, int = 0);
void display_window2(int = 0, int = 0, int = 0, int = 0, int = 0, int = 0);
void dmgcard(int = 0, int = 0);
void dmgplayer(int = 0, int = 0);
void draw_emo(int = 0, int = 0, int = 0);
void drawmenu(int = 0);
void eatstatus(int = 0, int = 0);
void efllistadd(int = 0, int = 0, int = 0, int = 0, int = 0, int = 0);
void egoadd(int = 0, int = 0);
void encremove(int = 0, int = 0, int = 0);
void eqrandweaponmage(int = 0);
void equipinfo(int = 0, int = 0, int = 0);
void evadd(int = 0, int = 0, int = 0);
void exittempinv();
void fileadd(const std::string&, int = 0);
void fillbg(int = 0, int = 0, int = 0, int = 0, int = 0);
void fix_input_chat(std::string&);
void fix_input_chat2(std::string&);
void fix_wish(std::string&);
void fixaiact(int = 0);
void flt(int = 0, int = 0);
void fltn(const std::string&);
void generatemoney(int = 0);
void getrandomcard(int = 0);
void gmes(const std::string&);
void gohostile();
void gravecard(int = 0);
void healcon(int = 0, int = 0, int = 0);
void healhp(int = 0, int = 0);
void healmp(int = 0, int = 0);
void healsan(int = 0, int = 0);
void healsp(int = 0, int = 0);
void help_halt();
void hostileaction(int = 0, int = 0);
void ibitmod(int = 0, int = 0, int = 0);
void imeset(int = 0);
void incognitobegin();
void incognitoend();
void initcard(int = 0, int = 0, int = 0);
void inv_getheader(int = 0);
void item_acid(int = 0, int = 0);
void item_checkknown(int = 0);
void item_compress(int = 0);
void item_copy(int = 0, int = 0);
void item_delete(int = 0);
void item_exchange(int = 0, int = 0);
void item_num(int = 0, int = 0);
void itemlist(int = 0, int = 0);
void itemturn(int = 0);
void key_check(int = 0);
void keyrelease();
void label_0002();
void label_0026();
void label_0029();
void label_0030();
void label_0031();
void label_0034();
void label_0041();
void label_0043();
void label_0066();
void label_0067();
void label_0068();
void label_0140();
void label_0149();
void label_0173();
void label_0174();
void label_0175();
void label_0176();
void label_0180();
void label_0181();
void label_0182();
void label_0183();
void label_0184();
void label_0185();
void label_0192();
void label_0193();
void label_0196();
void label_0200();
void label_0201();
void label_0202();
void label_0221();
void label_0230();
void label_0246();
void label_0247();
void label_0258();
void label_0259();
void label_0260();
void label_0261();
void label_0262();
void label_0263();
void label_0264();
void label_0265();
void label_0266();
void label_0267();
void label_0268();
void label_0311();
void label_0478();
void label_0481();
void label_1276();
void label_1277();
void label_1346();
void label_1370();
void label_1398();
void label_1399();
void label_1415();
void label_1416();
void label_1417();
void label_14170();
void label_1418();
void label_14180();
void label_1419();
void label_14190();
void label_1420();
void label_1421();
void label_1422();
void label_1423();
void label_1424();
void label_1425();
void label_1426();
void label_1428();
void label_1429();
void label_1433();
void label_1434();
void label_1435();
void label_1436();
void label_1437();
void label_1438();
void label_1439();
void label_1440();
void label_1441();
void label_1442();
void label_1443();
void label_1444();
void label_1445();
void label_1446();
void label_1452();
void label_1453();
void label_1454();
void label_1455();
void label_1456();
void label_1457();
void label_1458();
void label_1459();
void label_1460();
void label_1461();
void label_1462();
void label_1463();
void label_1464();
void label_1465();
void label_1466();
void label_1467();
void label_1468();
void label_1469();
void label_1470();
void label_1471();
void label_1472();
void label_1477();
void label_1512();
void label_1516();
void label_1519();
void label_1520();
void label_1521();
void label_1525();
void label_1530();
void label_1531();
void label_1532();
void label_1534();
void label_1535();
void label_1536();
void label_1537();
void label_1538();
void label_15380();
void label_1539();
void label_15390();
void label_1540();
void label_1541();
void label_1544();
void label_1560();
void label_1566();
void label_1572();
void label_1573();
void label_1576();
void label_1577();
void label_1578();
void label_1579();
void label_1580();
void label_1581();
void label_1583();
void label_1586();
void label_1587();
void label_1588();
void label_1589();
void label_1590();
void label_1591();
void label_1592();
void label_1593();
void label_1594();
void label_1595();
void label_1596();
void label_1597();
void label_1598();
void label_1599();
void label_1600();
void label_1601();
void label_1602();
void label_1603();
void label_1604();
void label_1605();
void label_1606();
void label_1607();
void label_1608();
void label_1609();
void label_1610();
void label_1611();
void label_1612();
void label_1613();
void label_1614();
void label_1615();
void label_1616();
void label_1617();
void label_1618();
void label_1666();
void label_16952();
void label_1696();
void label_1704();
void label_1705();
void label_1708();
void label_1709();
void label_1710();
void label_1711();
void label_1712();
void label_1713();
void label_1714();
void label_1723();
void label_1724();
void label_1725();
void label_1726();
void label_1727();
void label_1728();
void label_1729();
void label_1730();
void label_1733();
void label_1735();
void label_1736();
void label_1737();
void label_1738();
void label_1739();
void label_17402();
void label_1745();
void label_1746();
void label_1748();
void label_1749();
void label_1750();
void label_1751();
void label_1752();
void label_1754();
void label_1755();
void label_1773();
void label_1790();
void label_1793();
void label_1802();
void label_1815();
void label_1816();
void label_1817();
void label_1818();
void label_1819();
void label_1823();
void label_1824();
void label_1825();
void label_1826();
void label_1827();
void label_1828();
void label_1836();
void label_1839();
void label_1840();
void label_1842();
void label_1844();
void label_18462();
void label_1848();
void label_1854();
void label_18552();
void label_1859();
void label_1866();
void label_18672();
void label_1870();
void label_1871();
void label_1872();
void label_1873();
void label_1874();
void label_1876();
void label_1877();
void label_1878();
void label_1879();
void label_1882();
void label_1883();
void label_1884();
void label_1885();
void label_1886();
void label_1888();
void label_1889();
void label_1890();
void label_1891();
void label_1892();
void label_1901();
void label_1920();
void label_1921();
void label_1922();
void label_1924();
void label_1927();
void label_1933();
void label_19342();
void label_1935();
void label_1942();
void label_1951();
void label_1955();
void label_1958();
void label_1964();
int label_19672();
void label_1968();
int label_1969();
void label_1972();
void label_1976();
void label_1988();
void label_1992();
void label_1996();
void label_1997();
void label_2000();
void label_2001();
void label_2002();
void label_2003();
void label_2004();
void label_2005();
void label_2006();
void label_2007();
void label_2011();
void label_2012();
void label_2013();
void label_2022();
void label_2026();
void label_2027();
void label_2031();
void label_2032();
void label_2038();
void label_2047();
void label_2048();
void label_2049();
void label_2050();
void label_2054();
void label_2055();
void label_2056();
void label_2057();
void label_2068();
void label_2074();
void label_2076();
void label_2077();
void label_2078();
void label_2079();
void label_2081();
void label_2082();
void label_2084();
void label_2085();
void label_2086();
void label_2087();
void label_2088();
void label_2089();
void label_2090();
void label_2091();
void label_2092();
void label_2093();
void label_2095();
void label_2104();
void label_2105();
void label_2106();
void label_2108();
void label_2109();
void label_2110();
void label_2111();
void label_2112();
void label_2113();
void label_2114();
void label_2115();
void label_2118();
void label_2121();
void label_2124();
void label_21262();
void label_2134();
void label_2136();
void label_2138();
void label_2139();
void label_2140();
void label_2144();
void label_21452();
void label_2146();
void label_2147();
void label_2148();
void label_2149();
void label_2150();
void label_2151();
void label_2152();
void label_2153();
void label_2154();
void label_2155();
void label_2156();
void label_2157();
void label_2158();
void label_2159();
void label_2160();
void label_2161();
void label_2162();
void label_2187();
void label_2188();
void label_2189();
void label_2190();
void label_2191();
void label_2195();
void label_2196();
void label_2197();
void label_2198();
void label_2199();
void label_2200();
void label_2201();
void label_2203();
void label_2205();
void label_2206();
void label_2207();
void label_2212();
void label_2213();
void label_2214();
void label_2215();
void label_2216();
void label_2218();
void label_22192();
void label_2220();
void label_2221();
void label_2222();
void label_2223();
void label_2224();
void label_2227();
void label_2228();
void label_2232();
void label_2233();
void label_2234();
void label_2235();
void label_2236();
void label_2237();
void label_2241();
void label_2242();
void label_2243();
void label_2244();
void label_2246();
void label_2249();
void label_2250();
void label_2251();
void label_2252();
void label_2253();
void label_2254();
void label_2255();
void label_2256();
void label_2257();
void label_2259();
void label_2260();
void label_22600();
void label_2261();
void label_22610();
void label_2262();
void label_2263();
void label_2264();
void label_2265();
void label_2266();
void label_2267();
void label_2270();
void label_22712();
void label_2276();
void label_2280();
void label_2295();
void label_2296();
void label_2299();
void label_2655();
void label_2660();
void label_2661();
void label_2662();
void label_2663();
void label_2666();
void label_2667();
void label_2668();
void label_2669();
void label_2670();
void label_2671();
void label_2673();
void label_2674();
void label_2675();
void label_2676();
void label_2677();
void label_2678();
void label_2679();
void label_2680();
void label_2684();
void label_2685();
void label_2687();
void label_2690();
void label_2693();
void label_2696();
void label_2697();
void label_2700();
void label_2701();
void label_2702();
void label_2703();
void label_2707();
void label_2710();
void label_2713();
void label_2714();
void label_2715();
void label_2716();
void label_2719();
void label_2720();
void label_2723();
void label_2727();
void label_2731();
void label_2732();
void label_2733();
void label_2735();
void label_2736();
void label_27412();
void label_2742();
void label_2748();
void label_27492();
void label_2751();
void label_2752();
void label_2753();
void label_2754();
void lenfix(std::string&, int = 0);
void lovemiracle(int = 0);
void make_dish(int = 0, int = 0);
void make_sound(int = 0, int = 0, int = 0, int = 0, int = 0, int = 0);
void makecardlist();
void map_converttile();
void map_createroomdoor();
void map_initcustom(const std::string&);
void map_initialize();
void map_makedoor();
void map_nextdir1(int = 0, int = 0);
void map_nextdir2(int = 0, int = 0);
void map_placearena(int = 0, int = 0);
void map_placecharaonentrance(int = 0, int = 0, int = 0);
void map_placeplayer();
void map_randomtile(int = 0, int = 0);
void map_randsite(int = 0, int = 0);
void map_reload(const std::string&);
void map_setfog(int = 0, int = 0);
void map_tileset(int = 0);
void mapitem_cold(int = 0, int = 0);
void mapitem_fire(int = 0, int = 0);
void matdelmain(int = 0, int = 0);
void matgetmain(int = 0, int = 0, int = 0);
void modcorrupt(int = 0);
void modgrowth(int = 0, int = 0, int = 0);
void modheight(int = 0, int = 0);
void modimp(int = 0, int = 0);
void modkarma(int = 0, int = 0);
void modrank(int = 0, int = 0, int = 0);
void modweight(int = 0, int = 0, int = 0);
void msg_clear();
void msg_halt();
void msg_newline();
void msg_newlog();
void msg_write(std::string&);
void netload(const std::string&);
void opencard(int = 0);
void page_load();
void page_save();
void press(int = 0);
void put_questtarget();
void putenclv(int = 0);
void refreshspeed(int = 0);
void remain_make(int = 0, int = 0);
void removeitem(int = 0, int = 0);
void removeworker(int = 0);
void resistmod(int = 0, int = 0, int = 0);
void ride_begin(int = 0);
void ride_end();
void rm_crlf(std::string&);
void rowact_check(int = 0);
void rowact_item(int = 0);
void rowactend(int = 0);
void saccard(int = 0, int = 0);
void savecycle();
void setunid(int = 0, int = 0);
void showcard();
void showcard2(int = 0, int = 0);
void showcardholder();
void showcardpile();
void showeconomy(int, int, const std::string&, int = 0, int = 0);
void showscroll(int = 0, int = 0, int = 0, int = 0);
void showtitle(const std::string&, const std::string&, int = 0, int = 0);
void sickifcursed(int = 0, int = 0, int = 0);
void skillgain(int = 0, int = 0, int = 0, int = 0);
void skillinit(int = 0, int = 0, int = 0);
void snarmor(std::string&);
void snbakery(std::string&);
void snblack(std::string&);
void snd(int = 0, int = 0, int = 0);
void sndload(const std::string&, int = 0);
void snfish(std::string&);
void snfood(std::string&);
void sngeneral(std::string&);
void sngoods(std::string&);
void sninn(std::string&);
void snmagic(std::string&);
void sntrade(std::string&);
void sntrainer(std::string&);
void sortenc(int = 0);
void spillblood(int = 0, int = 0, int = 0);
void spillfrag(int = 0, int = 0, int = 0);
void stxt(int, const std::string&);
void tcgdeck();
void tcgdraw();
void tcgdrawbg();
void tcgdrawcard(int = 0, int = 0);
void tcginit();
void tcgmain();
void text_set();
void tmset();
void turn_aggro(int = 0, int = 0, int = 0);
void txt_check(int = 0);
void txt_conv();
void txtcontinue();
void txtef(int = 0);
void txteledmg(int = 0, int = 0, int = 0, int = 0);
void txtgod(int = 0, int = 0);
void txtmore();
void txtnew();
void txtsetlastword();
void txtsetwinword(int = 0);
void txttargetlevel();
void txttargetnpc(int = 0, int = 0, int = 0);
void unzip2(const std::string&, const std::string&);
void wake_up();
void wet(int = 0, int = 0);
void window(int = 0, int = 0, int = 0, int = 0, int = 0, int = 0);
void window2(int = 0, int = 0, int = 0, int = 0, int = 0, int = 0);
void window_recipe2();
void windowanime(int = 0, int = 0, int = 0, int = 0, int = 0, int = 0);
void windowanimecorner(int = 0, int = 0, int = 0, int = 0, int = 0, int = 0);
void zipadd(const std::string&);
void zipadd2(const std::string&);
void zipend2();
void zipinit2(const std::string&, const std::string&);
void cs_list(
    int CNT,
    const std::string& prm_543,
    int prm_544 = 0,
    int prm_545 = 0,
    int prm_546 = 0,
    int prm_547 = 0,
    int prm_548 = 0,
    int prm_549 = 0);


template <typename T>
void txt()
{
    static_assert(false_v<T>);
}


inline std::string txt_tostr(const std::string& s)
{
    return s;
}


inline std::string txt_tostr(elona_vector1<std::string>& v)
{
    return v(0);
}


template <typename... Args>
void txt(Args&&... args)
{
    std::vector<std::string> text{txt_tostr(args)...};
    txtvalid = 0;
    if (hear != 0)
    {
        snd(hear);
        hear = 0;
    }
    msgtemp = text[rnd(std::size(text))];
    txt_conv();
    tcol_at_txtfunc(0) = 255;
    tcol_at_txtfunc(1) = 255;
    tcol_at_txtfunc(2) = 255;
}



struct elona_fmode_t
{
    enum class Type
    {
        integer,
        string,
    } type;

    // FIXME: Use union.
    int i;
    std::string s;

    elona_fmode_t()
        : type(Type::integer)
        , i(0)
    {
    }

    virtual ~elona_fmode_t() = default;

    bool operator==(int i) const noexcept
    {
        return type == Type::integer && this->i == i;
    }

    bool operator==(const std::string& s) const noexcept
    {
        return type == Type::string && this->s == s;
    }

    elona_fmode_t& operator=(int i)
    {
        type = Type::integer;
        this->i = i;
        s.clear();
        return *this;
    }

    elona_fmode_t& operator=(const std::string& s)
    {
        type = Type::string;
        this->s = s;
        i = 0;
        return *this;
    }


    std::string to_string() const
    {
        switch (type)
        {
        case elona_fmode_t::Type::integer: return std::to_string(i);
        case elona_fmode_t::Type::string: return s;
        }
        assert(0);
    }
};



inline std::string operator+(const std::string& lhs, const elona_fmode_t& rhs)
{
    return lhs + rhs.to_string();
}


inline elona_fmode_t fmode;



} // namespace elona
