using namespace snail;

// Included in keybind.cpp.
// Keys not in this map should not be bound.
std::unordered_map<snail::Key, std::string> key_names = {
    {Key::key_0, "0"},
    {Key::key_1, "1"},
    {Key::key_2, "2"},
    {Key::key_3, "3"},
    {Key::key_4, "4"},
    {Key::key_5, "5"},
    {Key::key_6, "6"},
    {Key::key_7, "7"},
    {Key::key_8, "8"},
    {Key::key_9, "9"},

    {Key::key_a, "a"},
    {Key::key_b, "b"},
    {Key::key_c, "c"},
    {Key::key_d, "d"},
    {Key::key_e, "e"},
    {Key::key_f, "f"},
    {Key::key_g, "g"},
    {Key::key_h, "h"},
    {Key::key_i, "i"},
    {Key::key_j, "j"},
    {Key::key_k, "k"},
    {Key::key_l, "l"},
    {Key::key_m, "m"},
    {Key::key_n, "n"},
    {Key::key_o, "o"},
    {Key::key_p, "p"},
    {Key::key_q, "q"},
    {Key::key_r, "r"},
    {Key::key_s, "s"},
    {Key::key_t, "t"},
    {Key::key_u, "u"},
    {Key::key_v, "v"},
    {Key::key_w, "w"},
    {Key::key_x, "x"},
    {Key::key_y, "y"},
    {Key::key_z, "z"},

    {Key::f1, "F1"},
    {Key::f2, "F2"},
    {Key::f3, "F3"},
    {Key::f4, "F4"},
    {Key::f5, "F5"},
    {Key::f6, "F6"},
    {Key::f7, "F7"},
    {Key::f8, "F8"},
    {Key::f9, "F9"},
    {Key::f10, "F10"},
    {Key::f11, "F11"},
    {Key::f12, "F12"},
    {Key::f13, "F13"},
    {Key::f14, "F14"},
    {Key::f15, "F15"},
    {Key::f16, "F16"},
    {Key::f17, "F17"},
    {Key::f18, "F18"},
    {Key::f19, "F19"},
    {Key::f20, "F20"},
    {Key::f21, "F21"},
    {Key::f22, "F22"},
    {Key::f23, "F23"},
    {Key::f24, "F24"},

    {Key::insert, "Insert"},
    {Key::clear, "Clear"},

    {Key::home, "Home"},
    {Key::end, "End"},
    {Key::pageup, "Page Up"},
    {Key::pagedown, "Page Down"},

    {Key::application, "Application"},
    {Key::printscreen, "Print Screen"},

    {Key::space, "Space"},
    {Key::tab, "Tab"},
    {Key::backspace, "Backspace"},
    {Key::delete_, "Delete"},

    {Key::equal, "="},
    {Key::backquote, "`"},
    {Key::quote, "'"},
    {Key::backslash, "\\"},
    {Key::comma, ","},
    {Key::minus, "-"},
    {Key::period, "."},
    {Key::rightbracket, "}"},
    {Key::leftbracket, "{"},
    {Key::semicolon, ";"},
    {Key::slash, ","},
    {Key::ampersand, "&"},
    {Key::asterisk, "*"},
    {Key::at, "@"},
    {Key::caret, "^"},
    {Key::colon, ":"},
    {Key::dollar, "$"},
    {Key::exclaim, "!"},
    {Key::greater, ">"},
    {Key::hash, "#"},
    {Key::leftparen, "("},
    {Key::less, "<"},
    {Key::percent, "%"},
    {Key::plus, "+"},
    {Key::question, "?"},
    {Key::quotedbl, "\""},
    {Key::rightparen, ")"},
    {Key::underscore, "_"},

    {Key::keypad_0, "Keypad 0"},
    {Key::keypad_1, "Keypad 1"},
    {Key::keypad_2, "Keypad 2"},
    {Key::keypad_3, "Keypad 3"},
    {Key::keypad_4, "Keypad 4"},
    {Key::keypad_5, "Keypad 5"},
    {Key::keypad_6, "Keypad 6"},
    {Key::keypad_7, "Keypad 7"},
    {Key::keypad_8, "Keypad 8"},
    {Key::keypad_9, "Keypad 9"},
    {Key::keypad_a, "Keypad a"},
    {Key::keypad_b, "Keypad b"},
    {Key::keypad_c, "Keypad c"},
    {Key::keypad_d, "Keypad d"},
    {Key::keypad_e, "Keypad e"},
    {Key::keypad_f, "Keypad f"},

    {Key::keypad_backspace, "Keypad Backspace"},

    {Key::keypad_space, "Keypad Space"},
    {Key::keypad_tab, "Keypad Tab"},

    {Key::keypad_period, "Keypad ."},
    {Key::keypad_plus, "Keypad +"},
    {Key::keypad_minus, "Keypad -"},
    {Key::keypad_asterisk, "Keypad *"},
    {Key::keypad_slash, "Keypad /"},
    {Key::keypad_plusminus, "Keypad +-"},
    {Key::keypad_enter, "Keypad Enter"},
    {Key::keypad_equal, "Keypad ="},
};
