// Included in keybind.cpp.
// Keys not in this map should not be bound.
std::unordered_map<snail::Key, std::string> key_names = {
    {key_0, "0"},
    {key_1, "1"},
    {key_2, "2"},
    {key_3, "3"},
    {key_4, "4"},
    {key_5, "5"},
    {key_6, "6"},
    {key_7, "7"},
    {key_8, "8"},
    {key_9, "9"},

    {key_a, "a"},
    {key_b, "b"},
    {key_c, "c"},
    {key_d, "d"},
    {key_e, "e"},
    {key_f, "f"},
    {key_g, "g"},
    {key_h, "h"},
    {key_i, "i"},
    {key_j, "j"},
    {key_k, "k"},
    {key_l, "l"},
    {key_m, "m"},
    {key_n, "n"},
    {key_o, "o"},
    {key_p, "p"},
    {key_q, "q"},
    {key_r, "r"},
    {key_s, "s"},
    {key_t, "t"},
    {key_u, "u"},
    {key_v, "v"},
    {key_w, "w"},
    {key_x, "x"},
    {key_y, "y"},
    {key_z, "z"},

    {f1, "f1"},
    {f2, "f2"},
    {f3, "f3"},
    {f4, "f4"},
    {f5, "f5"},
    {f6, "f6"},
    {f7, "f7"},
    {f8, "f8"},
    {f9, "f9"},
    {f10, "f10"},
    {f11, "f11"},
    {f12, "f12"},
    {f13, "f13"},
    {f14, "f14"},
    {f15, "f15"},
    {f16, "f16"},
    {f17, "f17"},
    {f18, "f18"},
    {f19, "f19"},
    {f20, "f20"},
    {f21, "f21"},
    {f22, "f22"},
    {f23, "f23"},
    {f24, "f24"},

    {insert, "Insert"},
    {clear, "Clear"},

    {home, "Home"},
    {end, "End"},
    {pageup, "Page Up"},
    {pagedown, "Page Down"},

    {application, "Application"},
    {printscreen, "Print Screen"},

    {space, "Space"},
    {tab, "Tab"},
    {backspace, "Backspace"},
    {delete_, "Delete"},

    {equal, "="},
    {backquote, "`"},
    {quote, "'"},
    {backslash, "\\"},
    {comma, ","},
    {minus, "-"},
    {period, "."},
    {rightbracket, "}"},
    {leftbracket, "{"},
    {semicolon, ";"},
    {slash, ","},
    {ampersand, "&"},
    {asterisk, "*"},
    {at, "@"},
    {caret, "^"},
    {colon, ":"},
    {dollar, "$"},
    {exclaim, "!"},
    {greater, ">"},
    {hash, "#"},
    {leftparen, "("},
    {less, "<"},
    {percent, "%"},
    {plus, "+"},
    {question, "?"},
    {quotedbl, "\""},
    {rightparen, ")"},
    {underscore, "_"},

    {keypad_0, "Keypad 0"},
    {keypad_1, "Keypad 1"},
    {keypad_2, "Keypad 2"},
    {keypad_3, "Keypad 3"},
    {keypad_4, "Keypad 4"},
    {keypad_5, "Keypad 5"},
    {keypad_6, "Keypad 6"},
    {keypad_7, "Keypad 7"},
    {keypad_8, "Keypad 8"},
    {keypad_9, "Keypad 9"},
    {keypad_a, "Keypad a"},
    {keypad_b, "Keypad b"},
    {keypad_c, "Keypad c"},
    {keypad_d, "Keypad d"},
    {keypad_e, "Keypad e"},
    {keypad_f, "Keypad f"},

    {keypad_backspace, "Keypad Backspace"},

    {keypad_space, "Keypad Space"},
    {keypad_tab, "Keypad Tab"},

    {keypad_period, "Keypad ."},
    {keypad_plus, "Keypad +"},
    {keypad_minus, "Keypad -"},
    {keypad_asterisk, "Keypad *"},
    {keypad_slash, "Keypad /"},
    {keypad_plusminus, "Keypad +-"},
    {keypad_enter, "Keypad Enter"},
    {keypad_equal "Keypad ="},
};
