#pragma once

#define SCREEN_ORIENTATION_LANDSCAPE         0x0
#define SCREEN_ORIENTATION_PORTRAIT          0x1
#define SCREEN_ORIENTATION_SENSOR            0x4
#define SCREEN_ORIENTATION_SENSOR_LANDSCAPE  0x6
#define SCREEN_ORIENTATION_SENSOR_PORTRAIT   0x7
#define SCREEN_ORIENTATION_REVERSE_LANDSCAPE 0x8
#define SCREEN_ORIENTATION_REVERSE_PORTRAIT  0x9
